import type { Muscle } from "../exercises/muscles";

export interface WarmupCatalogEntry {
  slug: string;
  name: string;
  /** Warm-ups are only ever logged for reps ("bodyweight") or for time. */
  trackingType: "bodyweight" | "time";
  equipment: string;
  primaryMuscles: readonly Muscle[];
  secondaryMuscles: readonly Muscle[];
  instructions: readonly string[];
}

/**
 * Common warm-ups and stretches (issue #59), seeded as global catalog rows
 * alongside free-exercise-db (packages/db's seed) so every user has them.
 * Together they cover every muscle group in the controlled vocabulary —
 * warmups.test.ts holds that line. Slugs carry a "warmup-" prefix so they
 * can never collide with a free-exercise-db slug.
 */
export const WARMUP_EXERCISES: readonly WarmupCatalogEntry[] = [
  {
    slug: "warmup-jumping-jacks",
    name: "Jumping Jacks",
    trackingType: "time",
    equipment: "body only",
    primaryMuscles: ["calves", "shoulders"],
    secondaryMuscles: ["quadriceps", "glutes", "abductors"],
    instructions: [
      "Stand tall with feet together and arms at your sides.",
      "Jump your feet out wide while raising your arms overhead.",
      "Jump back to the start and keep a steady, easy rhythm.",
    ],
  },
  {
    slug: "warmup-arm-circles",
    name: "Arm Circles",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["traps"],
    instructions: [
      "Stand with arms straight out to the sides at shoulder height.",
      "Make small circles, gradually growing them larger.",
      "Reverse direction halfway through.",
    ],
  },
  {
    slug: "warmup-neck-rolls",
    name: "Neck Rolls",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["neck"],
    secondaryMuscles: ["traps"],
    instructions: [
      "Stand or sit tall with shoulders relaxed.",
      "Slowly roll your head in a half circle from shoulder to shoulder.",
      "Keep the movement slow and pain-free; avoid dropping the head back.",
    ],
  },
  {
    slug: "warmup-neck-side-stretch",
    name: "Neck Side Stretch",
    trackingType: "time",
    equipment: "body only",
    primaryMuscles: ["neck"],
    secondaryMuscles: ["traps"],
    instructions: [
      "Sit or stand tall and tilt your ear toward one shoulder.",
      "Rest the same-side hand lightly on your head for a gentle stretch.",
      "Hold, then switch sides.",
    ],
  },
  {
    slug: "warmup-shoulder-shrug-rolls",
    name: "Shoulder Shrug Rolls",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["traps"],
    secondaryMuscles: ["shoulders", "neck"],
    instructions: [
      "Stand tall with arms relaxed at your sides.",
      "Shrug your shoulders up, roll them back and down in a smooth circle.",
      "Reverse direction halfway through.",
    ],
  },
  {
    slug: "warmup-cross-body-shoulder-stretch",
    name: "Cross-Body Shoulder Stretch",
    trackingType: "time",
    equipment: "body only",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["middle back", "triceps"],
    instructions: [
      "Bring one arm straight across your chest.",
      "Use the other forearm to gently pull it closer to your body.",
      "Hold, then switch arms.",
    ],
  },
  {
    slug: "warmup-band-shoulder-dislocates",
    name: "Band Shoulder Dislocates",
    trackingType: "bodyweight",
    equipment: "bands",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["chest", "middle back"],
    instructions: [
      "Hold a band (or stick) with a wide overhand grip in front of your hips.",
      "Keeping arms straight, raise it overhead and down behind your back.",
      "Return the same way. Widen your grip if it pinches.",
    ],
  },
  {
    slug: "warmup-doorway-chest-stretch",
    name: "Doorway Chest Stretch",
    trackingType: "time",
    equipment: "body only",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders", "biceps"],
    instructions: [
      "Place your forearms on either side of a doorway, elbows at shoulder height.",
      "Step one foot through and lean forward until you feel the chest open.",
      "Hold without shrugging your shoulders.",
    ],
  },
  {
    slug: "warmup-scapular-push-up",
    name: "Scapular Push-Up",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["chest", "shoulders"],
    secondaryMuscles: ["triceps", "middle back"],
    instructions: [
      "Get into a high plank with arms straight.",
      "Without bending your elbows, let your chest sink between your shoulder blades.",
      "Push the floor away to spread the shoulder blades apart. Repeat.",
    ],
  },
  {
    slug: "warmup-overhead-triceps-stretch",
    name: "Overhead Triceps Stretch",
    trackingType: "time",
    equipment: "body only",
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["lats", "shoulders"],
    instructions: [
      "Raise one arm overhead and bend the elbow so your hand drops behind your head.",
      "Use the other hand to gently press the elbow back.",
      "Hold, then switch arms.",
    ],
  },
  {
    slug: "warmup-wall-biceps-stretch",
    name: "Wall Biceps Stretch",
    trackingType: "time",
    equipment: "body only",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["chest", "forearms"],
    instructions: [
      "Place your palm flat on a wall behind you at shoulder height, arm straight.",
      "Slowly turn your body away from the wall until you feel the stretch.",
      "Hold, then switch arms.",
    ],
  },
  {
    slug: "warmup-wrist-circles",
    name: "Wrist Circles",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["forearms"],
    secondaryMuscles: [],
    instructions: [
      "Interlace your fingers or make loose fists in front of you.",
      "Rotate your wrists in slow circles.",
      "Reverse direction halfway through.",
    ],
  },
  {
    slug: "warmup-wrist-flexor-stretch",
    name: "Wrist Flexor Stretch",
    trackingType: "time",
    equipment: "body only",
    primaryMuscles: ["forearms"],
    secondaryMuscles: ["biceps"],
    instructions: [
      "Extend one arm in front of you, palm up.",
      "Use the other hand to gently pull the fingers down and back.",
      "Hold, then switch hands.",
    ],
  },
  {
    slug: "warmup-dead-hang",
    name: "Dead Hang",
    trackingType: "time",
    equipment: "other",
    primaryMuscles: ["lats", "forearms"],
    secondaryMuscles: ["shoulders"],
    instructions: [
      "Grab a pull-up bar with an overhand grip, hands shoulder-width.",
      "Hang with arms straight and let your shoulders stretch upward.",
      "Keep your feet off the floor and breathe slowly.",
    ],
  },
  {
    slug: "warmup-band-pull-apart",
    name: "Band Pull-Apart",
    trackingType: "bodyweight",
    equipment: "bands",
    primaryMuscles: ["middle back", "shoulders"],
    secondaryMuscles: ["traps"],
    instructions: [
      "Hold a light band in front of you at shoulder height, arms straight.",
      "Pull the band apart by squeezing your shoulder blades together.",
      "Return slowly under control.",
    ],
  },
  {
    slug: "warmup-thoracic-open-book",
    name: "Thoracic Open Book",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["middle back"],
    secondaryMuscles: ["chest", "lower back"],
    instructions: [
      "Lie on your side with knees bent and arms stretched out in front, palms together.",
      "Open the top arm up and over to the other side, following it with your eyes.",
      "Return slowly. Finish the reps, then switch sides.",
    ],
  },
  {
    slug: "warmup-cat-cow",
    name: "Cat-Cow",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["lower back"],
    secondaryMuscles: ["abdominals", "middle back"],
    instructions: [
      "Start on hands and knees, wrists under shoulders and knees under hips.",
      "Round your back up toward the ceiling (cat).",
      "Then let your belly drop and lift your chest (cow). Alternate slowly.",
    ],
  },
  {
    slug: "warmup-childs-pose",
    name: "Child's Pose",
    trackingType: "time",
    equipment: "body only",
    primaryMuscles: ["lats", "lower back"],
    secondaryMuscles: ["shoulders", "glutes"],
    instructions: [
      "Kneel and sit your hips back toward your heels.",
      "Reach your arms forward along the floor and rest your forehead down.",
      "Breathe into your back and hold.",
    ],
  },
  {
    slug: "warmup-cobra-stretch",
    name: "Cobra Stretch",
    trackingType: "time",
    equipment: "body only",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: ["lower back", "chest"],
    instructions: [
      "Lie face down with hands under your shoulders.",
      "Press up to lift your chest, keeping hips on the floor.",
      "Hold with shoulders relaxed away from your ears.",
    ],
  },
  {
    slug: "warmup-dead-bug",
    name: "Dead Bug",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: ["lower back"],
    instructions: [
      "Lie on your back with arms toward the ceiling and knees bent at 90°.",
      "Lower the opposite arm and leg toward the floor, keeping your low back flat.",
      "Return and alternate sides.",
    ],
  },
  {
    slug: "warmup-hip-circles",
    name: "Hip Circles",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["abductors", "adductors", "lower back"],
    instructions: [
      "Stand with hands on hips and feet shoulder-width apart.",
      "Draw big, slow circles with your hips.",
      "Reverse direction halfway through.",
    ],
  },
  {
    slug: "warmup-leg-swings",
    name: "Leg Swings",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["hamstrings", "adductors"],
    secondaryMuscles: ["abductors", "glutes", "quadriceps"],
    instructions: [
      "Hold a wall or rack for balance.",
      "Swing one leg forward and back, gradually increasing the range.",
      "Then swing it side to side across your body. Switch legs.",
    ],
  },
  {
    slug: "warmup-hip-flexor-stretch",
    name: "Kneeling Hip Flexor Stretch",
    trackingType: "time",
    equipment: "body only",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes", "abdominals"],
    instructions: [
      "Kneel on one knee with the other foot flat in front of you.",
      "Squeeze the glute of the kneeling leg and shift your hips forward.",
      "Hold, then switch sides.",
    ],
  },
  {
    slug: "warmup-standing-quad-stretch",
    name: "Standing Quad Stretch",
    trackingType: "time",
    equipment: "body only",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: [],
    instructions: [
      "Stand tall and hold something for balance if needed.",
      "Pull one heel toward your glute, knees together.",
      "Hold, then switch legs.",
    ],
  },
  {
    slug: "warmup-standing-hamstring-stretch",
    name: "Standing Hamstring Stretch",
    trackingType: "time",
    equipment: "body only",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["lower back", "calves"],
    instructions: [
      "Place one heel on a low step or bench with the leg straight.",
      "Hinge forward at the hips with a flat back until you feel the stretch.",
      "Hold, then switch legs.",
    ],
  },
  {
    slug: "warmup-butterfly-stretch",
    name: "Butterfly Stretch",
    trackingType: "time",
    equipment: "body only",
    primaryMuscles: ["adductors"],
    secondaryMuscles: ["glutes"],
    instructions: [
      "Sit with the soles of your feet together and knees out to the sides.",
      "Hold your feet and sit tall.",
      "Gently press your knees toward the floor and hold.",
    ],
  },
  {
    slug: "warmup-cossack-squat",
    name: "Cossack Squat",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["adductors"],
    secondaryMuscles: ["quadriceps", "glutes", "hamstrings"],
    instructions: [
      "Stand with a very wide stance, toes slightly out.",
      "Shift your weight to one side and sit into that hip, keeping the other leg straight.",
      "Push back to center and alternate sides.",
    ],
  },
  {
    slug: "warmup-pigeon-stretch",
    name: "Pigeon Stretch",
    trackingType: "time",
    equipment: "body only",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["abductors", "lower back"],
    instructions: [
      "From hands and knees, bring one knee forward behind your wrist, shin angled across.",
      "Extend the back leg straight behind you.",
      "Sink your hips down and hold, then switch sides.",
    ],
  },
  {
    slug: "warmup-glute-bridge",
    name: "Glute Bridge",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "lower back"],
    instructions: [
      "Lie on your back with knees bent and feet flat, hip-width apart.",
      "Drive through your heels to lift your hips until your body is straight.",
      "Squeeze your glutes at the top, then lower slowly.",
    ],
  },
  {
    slug: "warmup-fire-hydrant",
    name: "Fire Hydrant",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["abductors"],
    secondaryMuscles: ["glutes"],
    instructions: [
      "Start on hands and knees.",
      "Keeping the knee bent, lift one leg out to the side to hip height.",
      "Lower under control. Finish the reps, then switch sides.",
    ],
  },
  {
    slug: "warmup-calf-wall-stretch",
    name: "Calf Wall Stretch",
    trackingType: "time",
    equipment: "body only",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    instructions: [
      "Place your hands on a wall and step one foot back, heel down.",
      "Keep the back leg straight and lean into the wall.",
      "Hold, then switch legs.",
    ],
  },
  {
    slug: "warmup-ankle-circles",
    name: "Ankle Circles",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    instructions: [
      "Lift one foot off the floor, holding something for balance if needed.",
      "Rotate the ankle in slow, full circles.",
      "Reverse direction, then switch feet.",
    ],
  },
  {
    slug: "warmup-bodyweight-squat",
    name: "Bodyweight Squat",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes", "hamstrings"],
    instructions: [
      "Stand with feet shoulder-width apart, toes slightly out.",
      "Sit your hips back and down as low as is comfortable, chest up.",
      "Stand back up through your whole foot.",
    ],
  },
  {
    slug: "warmup-walking-lunge",
    name: "Walking Lunge",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["quadriceps", "glutes"],
    secondaryMuscles: ["hamstrings", "calves"],
    instructions: [
      "Step forward and lower until both knees are bent about 90°.",
      "Push through the front foot and step straight into the next lunge.",
      "Keep your torso upright throughout.",
    ],
  },
  {
    slug: "warmup-inchworm",
    name: "Inchworm",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["hamstrings", "shoulders"],
    secondaryMuscles: ["abdominals", "chest"],
    instructions: [
      "Stand tall, hinge forward and place your hands on the floor.",
      "Walk your hands out to a high plank.",
      "Walk your feet back up toward your hands and stand. Repeat.",
    ],
  },
  {
    slug: "warmup-worlds-greatest-stretch",
    name: "World's Greatest Stretch",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["hamstrings", "quadriceps"],
    secondaryMuscles: ["glutes", "middle back", "adductors"],
    instructions: [
      "Step into a deep lunge and place both hands on the floor inside the front foot.",
      "Drop the same-side elbow toward the instep, then rotate that arm up to the ceiling.",
      "Return, straighten the front leg to stretch the hamstring, then switch sides.",
    ],
  },
  // Added for Maddy's Workout Split (issue #141).
  {
    slug: "warmup-wall-ankle-mobilization",
    name: "Wall Ankle Mobilization",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    instructions: [
      "Face a wall in a half-kneeling or split stance, front toes a few inches from the wall.",
      "Keeping the heel down, drive the front knee forward over the toes to touch the wall.",
      "Return and repeat, then switch feet. Move the foot back as mobility improves.",
    ],
  },
  {
    slug: "warmup-four-way-ankle",
    name: "4-Way Ankle",
    trackingType: "bodyweight",
    equipment: "bands",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    instructions: [
      "Sit with one leg straight and a light band looped around the forefoot.",
      "Work the ankle against the band in all four directions: point, flex, turn in, turn out.",
      "Move slowly through the full range, then switch feet.",
    ],
  },
  {
    slug: "warmup-sumo-squat",
    name: "Sumo Squat",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["adductors", "glutes"],
    secondaryMuscles: ["quadriceps", "hamstrings"],
    instructions: [
      "Stand with feet wider than shoulder-width, toes turned out.",
      "Sit straight down between your heels, pushing your knees out over your toes.",
      "Pause at the bottom to open the hips, then stand back up.",
    ],
  },
  {
    slug: "warmup-hip-flexor-raise",
    name: "Hip Flexor Raise",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["abdominals"],
    instructions: [
      "Stand tall, holding a wall or rack for balance if needed.",
      "Drive one knee up as high as you can without leaning back, then lower with control.",
      "Repeat, then switch legs.",
    ],
  },
  {
    slug: "warmup-tibialis-raise",
    name: "Tibialis Raise",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    instructions: [
      "Lean your back against a wall with your heels a foot or so in front of you.",
      "Keeping your legs straight, pull your toes up toward your shins as high as you can.",
      "Lower slowly and repeat.",
    ],
  },
  {
    slug: "warmup-band-internal-external-rotation",
    name: "Band Internal/External Rotation",
    trackingType: "bodyweight",
    equipment: "bands",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["middle back"],
    instructions: [
      "Anchor a light band at elbow height and hold it with your elbow bent 90° and tucked to your side.",
      "Rotate your forearm away from your body (external), then back across (internal), keeping the elbow pinned.",
      "Turn to face the other way to load the other direction, then switch arms.",
    ],
  },
  {
    slug: "warmup-blackburns",
    name: "Blackburns",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["middle back", "shoulders"],
    secondaryMuscles: ["traps"],
    instructions: [
      "Lie face down with your forehead just off the floor and arms out to the sides, thumbs up.",
      "Squeeze your shoulder blades together and lift your arms slightly off the floor.",
      "Sweep the arms from your sides up overhead and back down without letting them touch the floor.",
    ],
  },
  {
    slug: "warmup-active-hamstring-stretch",
    name: "Active Hamstring Stretch",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["calves", "glutes"],
    instructions: [
      "Lie on your back with one leg straight on the floor.",
      "Raise the other leg as high as you can while keeping the knee straight.",
      "Lower with control and repeat, then switch legs.",
    ],
  },
  {
    slug: "warmup-heel-taps",
    name: "Heel Taps",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes"],
    instructions: [
      "Stand on a low step on one leg with the other foot hanging off the side.",
      "Slowly bend the standing knee until the free heel lightly taps the floor.",
      "Push back up without locking out, then switch legs.",
    ],
  },
  {
    slug: "warmup-leg-lifts",
    name: "Leg Lifts",
    trackingType: "bodyweight",
    equipment: "body only",
    primaryMuscles: ["abdominals"],
    secondaryMuscles: ["quadriceps"],
    instructions: [
      "Lie on your back with legs straight and hands under your hips.",
      "Keeping your lower back pressed down, lift both legs toward the ceiling.",
      "Lower slowly without letting your heels touch the floor. Repeat.",
    ],
  },
  {
    slug: "warmup-downward-dog",
    name: "Downward-Facing Dog",
    trackingType: "time",
    equipment: "body only",
    primaryMuscles: ["hamstrings", "calves"],
    secondaryMuscles: ["shoulders", "lats"],
    instructions: [
      "Start on hands and knees, then lift your hips up and back into an inverted V.",
      "Press your chest toward your thighs and your heels toward the floor.",
      "Hold, pedalling the feet gently if the calves are tight.",
    ],
  },
  {
    slug: "warmup-kneeling-lunge-fold",
    name: "Kneeling Lunge Fold",
    trackingType: "time",
    equipment: "body only",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["calves", "glutes"],
    instructions: [
      "Start in a kneeling lunge, then shift your hips back over the back knee.",
      "Straighten the front leg, flex the front foot and fold your chest over it.",
      "Hold, then switch legs.",
    ],
  },
  {
    slug: "warmup-couch-stretch",
    name: "Kneeling Couch Stretch",
    trackingType: "time",
    equipment: "body only",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes", "abdominals"],
    instructions: [
      "Kneel with one shin up against a wall or couch behind you, the other foot forward in a lunge.",
      "Squeeze the back-leg glute and bring your torso upright until the front of the hip stretches.",
      "Hold, then switch legs.",
    ],
  },
];
